---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      ignore_warnings: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - ToDo
      - Todo
      - TO-DO
      - To-Do
      - HACK
      - Hack
      - HERE BE DRAGONS
      - Here Be Dragons
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- "build/"
- "build-server/"
- node_modules/
- "**/reports/**/*"
- "**/test/**/*"
- "**/config/**/*"
- "**/scripts/**/*"
