import actionsTypeDefs from "./actions";
import ambianceTypeDefs from "./ambiance";
import assetsTypeDefs from "./assets";
import clientsTypeDefs from "./clients";
import commandLineTypeDefs from "./commandLine";
import computerCoreTypeDefs from "./computerCore";
import coolantTypeDefs from "./coolant";
import coreFeedTypeDefs from "./coreFeed";
import coreLayoutsTypeDefs from "./coreLayouts";
import crewTypeDefs from "./crew";
import crmTypeDefs from "./crm";
import damageTypeDefs from "./damage";
import decksTypeDefs from "./decks";
import dockingTypeDefs from "./docking";
import enginesTypeDefs from "./engines";
import environmentTypeDefs from "./environment";
import exocompTypeDefs from "./exocomp";
import externalsTypeDefs from "./externals";
import flightTypeDefs from "./flight";
import googleSheetsTypeDefs from "./googleSheets";
import hullPlatingTypeDefs from './hullPlating'
import interfacesTypeDefs from "./interfaces";
import internalCommTypeDefs from "./internalComm";
import inventoryTypeDefs from "./inventory";
import isochipsTypeDefs from "./isochips";
import jumpDriveTypeDefs from "./jumpDrive";
import keyboardTypeDefs from "./keyboard";
import libraryTypeDefs from "./library";
import lightingTypeDefs from "./lighting";
import lrcommTypeDefs from "./lrcomm";
import macroTypeDefs from "./macro";
import messagesTypeDefs from "./messages";
import midiTypeDefs from "./midi";
import missionTypeDefs from "./mission";
import motuTypeDefs from "./motu";
import navigationTypeDefs from "./navigation";
import objectiveTypeDefs from "./objective";
import officerLogTypeDefs from "./officerLog";
import phasersTypeDefs from "./phasers";
import powerTypeDefs from "./power";
import probesTypeDefs from "./probes";
import railgunTypeDefs from "./railgun";
import reactorTypeDefs from "./reactor";
import recordsTypeDefs from "./records";
import roomsTypeDefs from "./rooms";
import scalarsTypeDefs from "./scalars";
import sensorsTypeDefs from "./sensors";
import setTypeDefs from "./set";
import shieldsTypeDefs from "./shields";
import shipTypeDefs from "./ship";
import shortRangeCommTypeDefs from "./shortRangeComm";
import sickbayTypeDefs from "./sickbay";
import signalJammerTypeDefs from "./signalJammer";
import simulatorTypeDefs from "./simulator";
import softwarePanelsTypeDefs from "./softwarePanels";
import stationTypeDefs from "./station";
import stealthFieldTypeDefs from "./stealthField";
import subspaceFieldTypeDefs from "./subspaceField";
import surveyFormTypeDefs from "./surveyForm";
import systemTypeDefs from "./system";
import tacticalMapTypeDefs from "./tacticalMap";
import targetingTypeDefs from "./targeting";
import taskReportTypeDefs from "./taskReport";
import tasksTypeDefs from "./tasks";
import teamsTypeDefs from "./teams";
import templateTypeDefs from "./template";
import thoriumTypeDefs from "./thorium";
import thrustersTypeDefs from "./thrusters";
import thxTypeDefs from "./thx";
import torpedosTypeDefs from "./torpedos";
import tractorBeamTypeDefs from "./tractorBeam";
import transportersTypeDefs from "./transporters";
import transwarpTypeDefs from "./transwarp";
import triggerTypeDefs from "./trigger";
import viewscreenTypeDefs from "./viewscreen";
import countermeasuresTypeDefs from "./countermeasures";
import universeTypeDefs from "./universe";
import dmxTypeDefs from "./dmx";
import taskFlowTypeDefs from "./taskFlow";
export * from "./universe/components";

export const actions = actionsTypeDefs;
export const ambiance = ambianceTypeDefs;
export const assets = assetsTypeDefs;
export const clients = clientsTypeDefs;
export const commandLine = commandLineTypeDefs;
export const computerCore = computerCoreTypeDefs;
export const coolant = coolantTypeDefs;
export const coreFeed = coreFeedTypeDefs;
export const coreLayouts = coreLayoutsTypeDefs;
export const crew = crewTypeDefs;
export const crm = crmTypeDefs;
export const damage = damageTypeDefs;
export const decks = decksTypeDefs;
export const docking = dockingTypeDefs;
export const engines = enginesTypeDefs;
export const environment = environmentTypeDefs;
export const exocomp = exocompTypeDefs;
export const externals = externalsTypeDefs;
export const flight = flightTypeDefs;
export const googleSheets = googleSheetsTypeDefs;
export const hullPlating = hullPlatingTypeDefs;
export const interfaces = interfacesTypeDefs;
export const internalComm = internalCommTypeDefs;
export const inventory = inventoryTypeDefs;
export const isochips = isochipsTypeDefs;
export const jumpDrive = jumpDriveTypeDefs;
export const keyboard = keyboardTypeDefs;
export const library = libraryTypeDefs;
export const lighting = lightingTypeDefs;
export const lrcomm = lrcommTypeDefs;
export const macro = macroTypeDefs;
export const messages = messagesTypeDefs;
export const midi = midiTypeDefs;
export const mission = missionTypeDefs;
export const motu = motuTypeDefs;
export const navigation = navigationTypeDefs;
export const objective = objectiveTypeDefs;
export const officerLog = officerLogTypeDefs;
export const phasers = phasersTypeDefs;
export const power = powerTypeDefs;
export const probes = probesTypeDefs;
export const railgun = railgunTypeDefs;
export const reactor = reactorTypeDefs;
export const records = recordsTypeDefs;
export const rooms = roomsTypeDefs;
export const scalars = scalarsTypeDefs;
export const sensors = sensorsTypeDefs;
export const set = setTypeDefs;
export const shields = shieldsTypeDefs;
export const ship = shipTypeDefs;
export const shortRangeComm = shortRangeCommTypeDefs;
export const sickbay = sickbayTypeDefs;
export const signalJammer = signalJammerTypeDefs;
export const simulator = simulatorTypeDefs;
export const softwarePanels = softwarePanelsTypeDefs;
export const station = stationTypeDefs;
export const stealthField = stealthFieldTypeDefs;
export const subspaceField = subspaceFieldTypeDefs;
export const surveyForm = surveyFormTypeDefs;
export const system = systemTypeDefs;
export const tacticalMap = tacticalMapTypeDefs;
export const targeting = targetingTypeDefs;
export const taskReport = taskReportTypeDefs;
export const tasks = tasksTypeDefs;
export const teams = teamsTypeDefs;
export const template = templateTypeDefs;
export const thorium = thoriumTypeDefs;
export const thrusters = thrustersTypeDefs;
export const thx = thxTypeDefs;
export const torpedos = torpedosTypeDefs;
export const tractorBeam = tractorBeamTypeDefs;
export const transporters = transportersTypeDefs;
export const transwarp = transwarpTypeDefs;
export const trigger = triggerTypeDefs;
export const viewscreen = viewscreenTypeDefs;
export const countermeasures = countermeasuresTypeDefs;
export const universe = universeTypeDefs;
export const dmx = dmxTypeDefs;
export const taskFlow = taskFlowTypeDefs;
