import actionsTypeDefs from "./actions.js";
import ambianceTypeDefs from "./ambiance.js";
import assetsTypeDefs from "./assets.js";
import clientsTypeDefs from "./clients.js";
import commandLineTypeDefs from "./commandLine.js";
import computerCoreTypeDefs from "./computerCore.js";
import coolantTypeDefs from "./coolant.js";
import coreFeedTypeDefs from "./coreFeed.js";
import coreLayoutsTypeDefs from "./coreLayouts.js";
import crewTypeDefs from "./crew.js";
import crmTypeDefs from "./crm.js";
import damageTypeDefs from "./damage.js";
import decksTypeDefs from "./decks.js";
import dockingTypeDefs from "./docking.js";
import enginesTypeDefs from "./engines.js";
import environmentTypeDefs from "./environment.js";
import exocompTypeDefs from "./exocomp.js";
import externalsTypeDefs from "./externals.js";
import flightTypeDefs from "./flight.js";
import googleSheetsTypeDefs from "./googleSheets.js";
import interfacesTypeDefs from "./interfaces.js";
import internalCommTypeDefs from "./internalComm.js";
import inventoryTypeDefs from "./inventory.js";
import isochipsTypeDefs from "./isochips.js";
import jumpDriveTypeDefs from "./jumpDrive.js";
import keyboardTypeDefs from "./keyboard.js";
import libraryTypeDefs from "./library.js";
import lightingTypeDefs from "./lighting.js";
import lrcommTypeDefs from "./lrcomm.js";
import macroTypeDefs from "./macro.js";
import messagesTypeDefs from "./messages.js";
import midiTypeDefs from "./midi.js";
import missionTypeDefs from "./mission.js";
import motuTypeDefs from "./motu.js";
import navigationTypeDefs from "./navigation.js";
import objectiveTypeDefs from "./objective.js";
import officerLogTypeDefs from "./officerLog.js";
import phasersTypeDefs from "./phasers.js";
import powerTypeDefs from "./power.js";
import probesTypeDefs from "./probes.js";
import railgunTypeDefs from "./railgun.js";
import reactorTypeDefs from "./reactor.js";
import recordsTypeDefs from "./records.js";
import roomsTypeDefs from "./rooms.js";
import scalarsTypeDefs from "./scalars.js";
import sensorsTypeDefs from "./sensors.js";
import setTypeDefs from "./set.js";
import shieldsTypeDefs from "./shields.js";
import shipTypeDefs from "./ship.js";
import shortRangeCommTypeDefs from "./shortRangeComm.js";
import sickbayTypeDefs from "./sickbay.js";
import signalJammerTypeDefs from "./signalJammer.js";
import simulatorTypeDefs from "./simulator";
import softwarePanelsTypeDefs from "./softwarePanels.js";
import stationTypeDefs from "./station.js";
import stealthFieldTypeDefs from "./stealthField.js";
import subspaceFieldTypeDefs from "./subspaceField.js";
import surveyFormTypeDefs from "./surveyForm.js";
import systemTypeDefs from "./system.js";
import tacticalMapTypeDefs from "./tacticalMap.js";
import targetingTypeDefs from "./targeting.js";
import taskReportTypeDefs from "./taskReport.js";
import tasksTypeDefs from "./tasks.js";
import teamsTypeDefs from "./teams.js";
import templateTypeDefs from "./template";
import thoriumTypeDefs from "./thorium.js";
import thrustersTypeDefs from "./thrusters.js";
import thxTypeDefs from "./thx.js";
import torpedosTypeDefs from "./torpedos.js";
import tractorBeamTypeDefs from "./tractorBeam.js";
import transportersTypeDefs from "./transporters.js";
import transwarpTypeDefs from "./transwarp.js";
import triggerTypeDefs from "./trigger.js";
import viewscreenTypeDefs from "./viewscreen.js";
import countermeasuresTypeDefs from "./countermeasures";

export const actions = actionsTypeDefs;
export const ambiance = ambianceTypeDefs;
export const assets = assetsTypeDefs;
export const clients = clientsTypeDefs;
export const commandLine = commandLineTypeDefs;
export const computerCore = computerCoreTypeDefs;
export const coolant = coolantTypeDefs;
export const coreFeed = coreFeedTypeDefs;
export const coreLayouts = coreLayoutsTypeDefs;
export const crew = crewTypeDefs;
export const crm = crmTypeDefs;
export const damage = damageTypeDefs;
export const decks = decksTypeDefs;
export const docking = dockingTypeDefs;
export const engines = enginesTypeDefs;
export const environment = environmentTypeDefs;
export const exocomp = exocompTypeDefs;
export const externals = externalsTypeDefs;
export const flight = flightTypeDefs;
export const googleSheets = googleSheetsTypeDefs;
export const interfaces = interfacesTypeDefs;
export const internalComm = internalCommTypeDefs;
export const inventory = inventoryTypeDefs;
export const isochips = isochipsTypeDefs;
export const jumpDrive = jumpDriveTypeDefs;
export const keyboard = keyboardTypeDefs;
export const library = libraryTypeDefs;
export const lighting = lightingTypeDefs;
export const lrcomm = lrcommTypeDefs;
export const macro = macroTypeDefs;
export const messages = messagesTypeDefs;
export const midi = midiTypeDefs;
export const mission = missionTypeDefs;
export const motu = motuTypeDefs;
export const navigation = navigationTypeDefs;
export const objective = objectiveTypeDefs;
export const officerLog = officerLogTypeDefs;
export const phasers = phasersTypeDefs;
export const power = powerTypeDefs;
export const probes = probesTypeDefs;
export const railgun = railgunTypeDefs;
export const reactor = reactorTypeDefs;
export const records = recordsTypeDefs;
export const rooms = roomsTypeDefs;
export const scalars = scalarsTypeDefs;
export const sensors = sensorsTypeDefs;
export const set = setTypeDefs;
export const shields = shieldsTypeDefs;
export const ship = shipTypeDefs;
export const shortRangeComm = shortRangeCommTypeDefs;
export const sickbay = sickbayTypeDefs;
export const signalJammer = signalJammerTypeDefs;
export const simulator = simulatorTypeDefs;
export const softwarePanels = softwarePanelsTypeDefs;
export const station = stationTypeDefs;
export const stealthField = stealthFieldTypeDefs;
export const subspaceField = subspaceFieldTypeDefs;
export const surveyForm = surveyFormTypeDefs;
export const system = systemTypeDefs;
export const tacticalMap = tacticalMapTypeDefs;
export const targeting = targetingTypeDefs;
export const taskReport = taskReportTypeDefs;
export const tasks = tasksTypeDefs;
export const teams = teamsTypeDefs;
export const template = templateTypeDefs;
export const thorium = thoriumTypeDefs;
export const thrusters = thrustersTypeDefs;
export const thx = thxTypeDefs;
export const torpedos = torpedosTypeDefs;
export const tractorBeam = tractorBeamTypeDefs;
export const transporters = transportersTypeDefs;
export const transwarp = transwarpTypeDefs;
export const trigger = triggerTypeDefs;
export const viewscreen = viewscreenTypeDefs;
export const countermeasures = countermeasuresTypeDefs;
