const viewList = [
"ShortRangeComm",
"LongRangeComm",
"AdminStations",
"EngineControl",
"Navigation",
"Thrusters",
"Sensors",
"AdminAssets",
"Transporters",
"Login",
"SecurityDecks",
"SecurityTeams",
"SecurityScans",
"ShieldControl",
"CommDecoding",
"Offline",
"CommInternal",
"Docking",
"CommShortRange",
"PowerDistribution",
"DamageControl",
"PowerDistributionBattery",
"Targeting",
"PhaserCharging",
"ProbeConstruction",
"StealthField",
"CargoControl",
"CoolantControl"
];

export default viewList;
