// Planet names from Endless Sky
export default [
  "Ablub's Invention",
  "Ada",
  "Ahr",
  "Albatross",
  "Alexandria",
  "Alfheim",
  "Allhome",
  "Alta Hai",
  "Amazon",
  "Antipode",
  "Arabia",
  "Arachne Station",
  "Aresepru Nat",
  "Asgard",
  "Ashy Reach",
  "Avalon",
  "Aventine",
  "Bank of Blugtad",
  "Belug's Plunge",
  "Big Sky",
  "Bivrost",
  "Bloodsea",
  "Bloptab's Furnace",
  "Blubipad's Workshop",
  "Blue Interior",
  "Bluestone",
  "Bounty",
  "Bourne",
  "Brass Second",
  "Bright Echo",
  "Buccaneer Bay",
  "Burthen",
  "Caelian",
  "Calda",
  "Canyon",
  "Carbuncle Station",
  "Ceaseless Toil",
  "Celestial Third",
  "Charon Station",
  "Charybdis Station",
  "Chiron",
  "Chosen Nexus",
  "Clark",
  "Clink",
  "Cloudfire",
  "Cold Horizon",
  "Cool Forest",
  "Cornucopia",
  "Corral of Meblumem",
  "Covert",
  "Crossroads",
  "Dancer",
  "Darkcloak",
  "Darkmetal",
  "Darkstone",
  "Darkwaste",
  "Deadman's Cove",
  "Deep",
  "Deep Treasure",
  "Deep Water",
  "Delve",
  "Delve of Bloptab",
  "Desi Seledrak",
  "Devru Kaska",
  "Diligent Hand",
  "Double Haze",
  "Drekag Firask",
  "Dune",
  "Dusk Companion",
  "Dustmaker",
  "Dwelling of Speloog",
  "Echo",
  "Elek Kartanu",
  "Ember Reaches",
  "Ember Threshold",
  "Ember Wormhole",
  "Esayaku Fen",
  "Esek Stovar",
  "Eskar Kortuka",
  "Esperaktu Station",
  "Factory of Eblumab",
  "Far Garden",
  "Far Home",
  "Far Monad",
  "Far'en Lai",
  "Fara Skaeruti",
  "Farpoint",
  "Farseer",
  "Farwater",
  "Featherweight",
  "Fek Rembatu",
  "Fenrir Station",
  "Firelode",
  "Firka Tesk",
  "Flood",
  "Flowing Fields",
  "Follower",
  "Forpelog",
  "Foundry",
  "Fourth Shadow",
  "Freedom",
  "Frostmark",
  "Furnace",
  "Geminus",
  "Gemstone",
  "Gentle Rain",
  "Geyser",
  "Giverstone",
  "Glaze",
  "Glittering Ice",
  "Glory",
  "Grakhord",
  "Greenbloom",
  "Greenrock",
  "Greenwater",
  "Gresku Fodar",
  "Hai-home",
  "Hammer of Debrugt",
  "Harmony",
  "Haven",
  "Haze",
  "Heartland",
  "Heartvalley",
  "Helheim",
  "Hephaestus",
  "Hermes",
  "Hestia",
  "Hippocrates",
  "Hope",
  "Hopper",
  "Huginn Station",
  "Humanika",
  "Hydra Station",
  "Icefall",
  "Icelake",
  "Ingot",
  "Inmost Blue",
  "Into White",
  "Karek Fornati",
  "Kasichara Fet",
  "Keneska Fek",
  "Kessel Sepret",
  "Ki Patek Ka",
  "Korati Efreti",
  "Korbatri Eska",
  "Kort Kehai",
  "Kort Vek'kri",
  "Kraken Station",
  "Kuwaru Efreti",
  "Lagrange",
  "Laki Nemparu",
  "Leviathan Station",
  "Lichen",
  "Lodestone",
  "Longjump",
  "Maelstrom",
  "Mainsail",
  "Maker",
  "Makerplace",
  "Mani",
  "Market of Gupta",
  "Martini",
  "Mebla's Portion",
  "Memory",
  "Merask Fortuno",
  "Mere",
  "Mereti Station",
  "Miblulub's Plenty",
  "Midgard",
  "Midway Emerald",
  "Millrace",
  "Mirrorlake",
  "Moonshake",
  "Muninn Station",
  "Muspel",
  "Mutiny",
  "Mystery",
  "Nasqueron",
  "Nearby Jade",
  "New Argentina",
  "New Austria",
  "New Boston",
  "New Britain",
  "New China",
  "New Finding",
  "New Greenland",
  "New Holland",
  "New Iceland",
  "New India",
  "New Kansas",
  "New Portland",
  "New Sahara",
  "New Switzerland",
  "New Tibet",
  "New Wales",
  "New Washington",
  "Newhome",
  "Nifel",
  "Nimbus",
  "Norn",
  "Oasis",
  "Oberon Station",
  "Oblivion",
  "Pearl",
  "Phoenix Station",
  "Pilot",
  "Placer",
  "Plort's Water",
  "Poisonwood",
  "Poseidos",
  "Prime",
  "Pugglemug",
  "Pugglequat",
  "Quicksilver",
  "Rand",
  "Refuge of Belugt",
  "Rekat Moraski",
  "Relic",
  "Remnant Wormhole",
  "Remote Blue",
  "Reunion",
  "Revelation",
  "Ring of Friendship",
  "Ring of Power",
  "Ring of Wisdom",
  "Rust",
  "Rusty Second",
  "Sabira Eseskrai",
  "Safaresk Enlai",
  "Sandy Two",
  "Sapira Mereti",
  "Sarisa Fentra",
  "Saros",
  "Sasirka Gatru",
  "Sebra Skira",
  "Second Cerulean",
  "Second Rose",
  "Second Viridian",
  "Secret Sky",
  "Sek Alarfarat",
  "Selefkar Refinery",
  "Seleptra Nak",
  "Separa Tiklar",
  "Septar Lorku",
  "Serpens",
  "Sessiliki Far",
  "Sestor Ikfar",
  "Setar Fort",
  "Shadow of Leaves",
  "Shadowed Valley",
  "Shangri-La",
  "Shifting Sand",
  "Shiver",
  "Shorebreak",
  "Shroud",
  "Silver",
  "Sinter",
  "Skillet",
  "Skyfarm",
  "Skymoot",
  "Slylandro",
  "Smuggler's Den",
  "Snowfeather",
  "Solace",
  "Solima Skarati",
  "Sopi Lefarkata",
  "Spera Anatrusk",
  "Splashdown",
  "Starcross",
  "Stonebreak",
  "Stormhold",
  "Stronghold of Flugbu",
  "Sundive",
  "Sundrinker",
  "Sunracer",
  "Tebuteb's Table",
  "Tefkar Ret",
  "Third Umber",
  "Thrall",
  "Thule",
  "Thunder",
  "Tik Klai",
  "Tinker",
  "Trinket",
  "Triton Station",
  "Trove",
  "Tundra",
  "Turquoise Four",
  "Twinstar",
  "Typhon Station",
  "Vail",
  "Valhalla",
  "Var' Kar'i'i",
  "Var' Kayi",
  "Var' Roi",
  "Vara K'chrai",
  "Vara Ke'sok",
  "Vara Ke'stai",
  "Vara Kehi'ki",
  "Vara Pug",
  "Vara Rakak",
  "Varu Ek'lak'lai",
  "Varu K'est",
  "Varu K'prai",
  "Varu Mer'ek",
  "Varu Tek'kai",
  "Varu Tev'kei",
  "Vibrant Water",
  "Viminal",
  "Vinci",
  "Warfeed",
  "Warm Slope",
  "Warm Wind",
  "Watcher",
  "Wayfarer",
  "Weir of Glubatub",
  "Windblain",
  "Winter",
  "Wormhole Alpha",
  "Wyvern Station",
  "Zenith",
  "Zug"
];
