import {ConfigObj} from "./generateDMXUniverse";

export default {
  "1": {
    main: {
      color: "rgb(255, 255, 255)",
      amber: "1",
      white: "1",
      uv: "0",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
    accent: {
      color: "rgb(255, 0, 0)",
      amber: "0",
      white: "0",
      uv: "0",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
  },
  "2": {
    main: {
      color: "rgb(255, 255, 255)",
      amber: "1",
      white: "1",
      uv: "0",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
    accent: {
      color: "rgb(255, 143, 0)",
      amber: "1",
      white: "0",
      uv: "0",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
  },
  "3": {
    main: {
      color: "rgb(255, 255, 255)",
      amber: "1",
      white: "1",
      uv: "0",
      intensity: "1",
      generic: "0",
      strobe: "0",
    },
    accent: {
      color: "rgb(251, 255, 0)",
      amber: "1",
      white: "0",
      uv: "0",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
  },
  "4": {
    main: {
      color: "rgb(255, 255, 255)",
      amber: "1",
      white: "1",
      uv: "0",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
    accent: {
      color: "rgb(48, 255, 0)",
      amber: "1",
      white: "1",
      uv: "0",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
  },
  "5": {
    main: {
      color: "rgb(255, 255, 255)",
      amber: "1",
      white: "1",
      uv: "0",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
    accent: {
      color: "rgb(0, 94, 255)",
      amber: "0",
      white: "1",
      uv: "0",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
  },
  p: {
    main: {
      color: "rgb(103, 103, 103)",
      amber: "0",
      white: "0",
      uv: "1",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
    accent: {
      color: "rgb(0, 0, 0)",
      amber: "0",
      white: "0",
      uv: "1",
      intensity: "1",
      strobe: "0",
      generic: "0",
    },
  },
  darken: {
    accent: {
      color: "rgb(255, 255, 255)",
      amber: "1",
      white: "1",
      uv: "0",
      intensity: "0.2",
      strobe: "0",
      generic: "0",
    },
    main: {
      intensity: "0",
      color: "rgb(0, 0, 0)",
      amber: "0",
      white: "0",
      uv: "0",
      strobe: "0",
      generic: "0",
    },
  },
} as ConfigObj;
