import appearanceTypedef from "./appearance";
import behaviorTypedef from "./behavior";
import identityTypedef from "./identity";
import locationTypedef from "./location";
import stageTypedef from "./stage";
import stageChildTypedef from "./stageChild";
import lightTypedef from "./light";
import glowTypedef from "./glow";
import templateTypedef from "./template";
import enginesTypedef from "./engines";
import thrustersTypedef from "./thrusters";

export const appearance = appearanceTypedef;
export const behavior = behaviorTypedef;
export const identity = identityTypedef;
export const location = locationTypedef;
export const stage = stageTypedef;
export const stageChild = stageChildTypedef;
export const light = lightTypedef;
export const glow = glowTypedef;
export const templateEntity = templateTypedef;
export const enginesEntity = enginesTypedef;
export const thrustersEntity = thrustersTypedef;
