export default {
  "CASM Generator": require("./parts/CASM Generator.svg"),
  "Field Emitter": require("./parts/Field Emitter.svg"),
  "Integrated Fluid Sensor": require("./parts/Integrated Fluid Sensor.svg"),
  "Power Coupling": require("./parts/Power Coupling.svg"),
  "Coaxial Servo": require("./parts/Coaxial Servo.svg"),
  "Field Generator": require("./parts/Field Generator.svg"),
  "Isolinear Circuit": require("./parts/Isolinear Circuit.svg"),
  "Power Splitter": require("./parts/Power Splitter.svg"),
  "Computer Interface": require("./parts/Computer Interface.svg"),
  "Fusion Generator": require("./parts/Fusion Generator.svg"),
  "Isolinear Programs": require("./parts/Isolinear Programs.svg"),
  "Prefire Chamber": require("./parts/Prefire Chamber.svg"),
  "Digital Sequencer": require("./parts/Digital Sequencer.svg"),
  "Fusion Welder": require("./parts/Fusion Welder.svg"),
  "Isolinear Rod": require("./parts/Isolinear Rod.svg"),
  "Residual Power Store": require("./parts/Residual Power Store.svg"),
  "EPS Power Node": require("./parts/EPS Power Node.svg"),
  "Gravity Generator": require("./parts/Gravity Generator.svg"),
  "Magnetic Bolt Fastener": require("./parts/Magnetic Bolt Fastener.svg"),
  "Sensor Grid": require("./parts/Sensor Grid.svg"),
  "EPS Step-Down Conduit": require("./parts/EPS Step-Down Conduit.svg"),
  "Holographic Servo Display": require("./parts/Holographic Servo Display.svg"),
  "Magnetic Coil": require("./parts/Magnetic Coil.svg"),
  "Subspace Transceiver": require("./parts/Subspace Transceiver.svg"),
  "Fiberoptic Wire Linkage": require("./parts/Fiberoptic Wire Linkage.svg"),
  "IDC Power Cable": require("./parts/IDC Power Cable.svg"),
  "Network Adapter": require("./parts/Network Adapter.svg")
};
