name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js, NPM
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install libs
        run: sudo apt-get install libudev-dev
      - name: Install Dependencies
        run: |
             npm i --force
             npm i --force @rollup/rollup-linux-x64-gnu
      - name: TypeScript Check
        run: |
          npm run typecheck
      - name: ESLint
        run: |
          npm run lint
      - name: Test
        env:
          SKIP_PREFLIGHT_CHECK: true
        run: |
          npm run test:plain
